#!/bin/bash

FLAG=""
NO_FORWARD=false

# parse commandline
while [ $# -gt 0 ]
do
      arg="$1"
      case "$arg" in
         --no-forward) NO_FORWARD=true; ;;
         -*) FLAG="$FLAG $1"; ;; # add flag
         *) break;; # not option, its some argument
       esac
       shift
done

# check if ~/.ssh/id_rsa.pub is in the file REMOTE:~/.ssh/authorized_keys
# if not, then "ssh-copy-id REMOTE"

if ssh -A $1 "[[ ! -e ~/.dotfiles-harrison/$DOTFILES_VERSION.version ]]" # assuming bash-like is the default shell
then
    echo "Transferring files..."
    ssh $1 "rm -rf ~/.dotfiles-harrison/*.version > /dev/null 2>&1" > /dev/null 2>&1
    tar c -C${HOME} -h -z --exclude-vcs .dotfiles-harrison | ssh $1 'tar mxz -C ${HOME}' > /dev/null 2>&1
    echo "Updated to $DOTFILES_VERSION"
fi

# maybe check if zsh is installed and if not install it? Or return an error?

if [ $NO_FORWARD == true ] ; then
    ssh $FLAG -t $1 "ZDOTDIR=~/.dotfiles-harrison/ zsh"
else
    ssh $FLAG -A -t $1 "ZDOTDIR=~/.dotfiles-harrison/ zsh"
fi
