#!/bin/bash

FLAG=""
NO_FORWARD=false

if [ $# -eq 0 ] ; then
    echo "Missing Hostname"
    exit 1
fi

# parse commandline
while [ $# -gt 0 ]
do
      arg="$1"
      case "$arg" in
         --no-forward) NO_FORWARD=true; ;;
         -*) FLAG="$FLAG $1"; ;; # add flag
         *) break;; # not option, its some argument
       esac
       shift
done

# check if ~/.ssh/id_rsa.pub is in the file REMOTE:~/.ssh/authorized_keys
# if not, then "ssh-copy-id REMOTE"

if ssh -A $1 "[[ ! -e ~/.dotfiles-harrison/$DOTFILES_VERSION.version ]]" # assuming bash-like is the default shell
then
    echo "Transferring files..."
    tar c -C${HOME} -h -z --exclude-vcs --exclude '.plugin_list' --exclude '.vim/*' .dotfiles-harrison | ssh $1 'tar mxz -C ${HOME} --no-same-owner --overwrite --recursive-unlink' > /dev/null 2>&1
    echo "Updated to $DOTFILES_VERSION"
fi

# maybe check if zsh is installed and if not install it? Or return an error?

if [ $NO_FORWARD == true ] ; then
    ssh $FLAG -t $1 "ZDOTDIR=~/.dotfiles-harrison/ $(which zsh)"
else
    ssh $FLAG -A -t $1 "ZDOTDIR=~/.dotfiles-harrison/ $(which zsh)"
fi
